name: "static-build-test-p4c"

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Build a p4c release on Ubuntu 20.04
  build-linux:
    strategy:
      fail-fast: false
    runs-on: ubuntu-latest
    env:
      CTEST_PARALLEL_LEVEL: 4
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
      with:
        key: static-${{ matrix.os }}
        max-size: 500M

    - name: Build (Linux)
      run: |
        ls -la
        ls -la ../
        ls -la ../..
        mkdir -p .ccache
        DOCKER_BUILDKIT=1 docker build -t p4c --build-arg IMAGE_TYPE=build --build-arg ENABLE_UNIFIED_COMPILATION=ON --build-arg BUILD_STATIC_RELEASE=ON --build-arg ENABLE_GMP=ON .
